export { default as HomePage } from './HomePage'
export { default as FeedbackPage } from './FeedbackPage'
export { default as AdminLogin } from './AdminLogin'
export { default as DashboardPage } from './DashboardPage'
export { default as NotFound } from './NotFound'
